export type Project = {
  slug: string;
  title: string;
  role: string;
  summary: string;
  tags: string[];
  tech: string[];
  featured: boolean;
  description: string;
  featuredGridImage?: string; // Path to featured image for grid view (e.g., '/images/portfolios/image.png')
  featuredImage?: string; // Path to featured image for detail page (e.g., '/images/portfolios/image.png')
  video?: string; // Path to video file (e.g., '/videos/project-demo.mp4')
  showOverlay?: boolean; // Whether to show the dark overlay on portfolio card images (default: true)
  caseStudySections?: {
    overview?: string;
    architecture?: string;
    uiux?: string;
    challenges?: string;
    impact?: string;
  };
};

export const projects: Project[] = [
  {
    slug: 'soundvent-social-network',
    title: 'SoundVent Social Network',
    role: 'Co-Founder & Lead Engineer',
    summary: 'The social networking system inside SoundVent is the connective tissue of the platform — a full-featured social graph that ties together artists, fans, labels, venues, and industry professionals. Instead of bolting on comments and likes as isolated features, I designed a unified system that powers feeds, profile walls, clips, and conversations from the same underlying model.',
    tags: ['Social Network', 'Music', 'SaaS', 'Next.js', 'Supabase', 'Real-time', 'Feed Engine'],
    tech: ['Next.js', 'React', 'Supabase', 'PostgreSQL', 'TypeScript', 'TailwindCSS', 'Zustand', 'Row-Level Security'],
    featured: true,
    featuredGridImage: '/images/portfolios/sv-social-network-grid.jpg',
    featuredImage: '/images/portfolios/sv-social-network.png',
    showOverlay: false,
    description: 'The social networking system inside SoundVent is the connective tissue of the platform — a full-featured social graph that ties together artists, fans, labels, venues, and industry professionals. Instead of bolting on comments and likes as isolated features, I designed a unified system that powers feeds, profile walls, clips, and conversations from the same underlying model.',
    caseStudySections: {
      overview: 'SoundVent\'s social layer is built to feel familiar to anyone who\'s used modern social apps, but tuned specifically for music culture. Users can:\n\n• Follow artists, fans, labels, venues, and other entities\n• Publish posts with rich media (images, video, links, clips)\n• Comment, reply, and hold threaded conversations\n• Like content at both post and comment levels\n• Reshare content into their own feed or profile wall\n\nThe same primitives drive multiple surfaces across the app:\n• Dashboard activity feeds\n• Public profile walls for artists, entities, and users\n• Discovery and "What\'s happening" style views\n• Social overlays around blogs, news, and marketplace content\n\nEvery follow, post, comment, and like feeds into a shared social graph that powers both the user experience and creator analytics — so the system isn\'t just "social noise," it\'s structured, queryable data.',
      architecture: 'Under the hood, the social system is a set of composable, entity-aware services built on top of Supabase. The goal was to keep the model simple, consistent, and reusable anywhere in the app without sacrificing security or clarity.\n\nKey architectural elements:\n\n• Unified Social Graph\nFollows, posts, comments, likes, and shares are all modeled in a shared graph. Any feature — from a dashboard widget to a full profile wall — can answer "who is connected to whom" and "who is engaging with what" using the same relationships and queries.\n\n• Entity-Aware Identity\nEvery social record stores both user_id (who performed the action) and entity_id (who they were acting as: band, venue, label, etc.). This lets users post "as themselves" or "as their project" while keeping attribution and permissions clean and auditable.\n\n• Feed Engine\nA dedicated feed layer merges social posts with industry content, applies follow- and context-aware ranking, and exposes a paginated API via shared hooks. It supports multiple modes (global, following-only, profile-specific) without duplicating logic.\n\n• Engagement Pipeline\nLikes, comments, replies, and shares all flow through structured endpoints that enforce idempotency, prevent double-actions, and emit notifications/analytics events. Engagement counts are derived from the data, not manually patched in the UI.\n\n• Short-Form Clips Layer\nTime-bound, snackable content (clips, micro-posts, promos) sits on top of the same social model, reusing identity, follow, and analytics patterns while optimizing for fast browsing and lightweight interaction.\n\nAll of this lives behind strict row-level security policies in Supabase, so even as the graph grows more complex, access control stays predictable and enforceable at the database level rather than scattered throughout the codebase.',
      uiux: 'The social UI is designed to feel like something you already know how to use — but tuned for how musicians and fans actually behave online. The goal was to surface connection and conversation in context, not force people into a separate "social" mode.\n\nSome UX highlights:\n\n• Dashboard Activity Feed\nA personalized stream that blends posts from followed accounts with curated industry content, using infinite scroll and lightweight filters to keep discovery fast and frictionless.\n\n• Profile Walls\nPublic timelines for artists, entities, and users that act as each profile\'s social home base — posts, shares, and engagement all in one place, aligned with SoundVent\'s visual system.\n\n• Inline Composer\nA post composer that supports mentions, rich media, visibility controls, and entity context — embedded directly into the places where users are already working and browsing, so posting doesn\'t feel like a chore.\n\n• Threaded Comments & Reactions\nConversations stay readable with clear hierarchy, subtle moderation cues, and responsive interactions on posts and replies. Reactions update quickly, with optimistic UI and smooth feedback.\n\n• Social Overlays & Mini-Feeds\nHover states, dialogs, and compact feeds let users explore networks and activity without losing their place. You can peek into a profile\'s social footprint without leaving your current workflow.\n\nThe visual language is consistent with the rest of SoundVent: dark, minimal, music-first, and focused on letting content and relationships take center stage.',
      challenges: '1. Supporting both people and entities in one network\nSoundVent isn\'t just individual users — people act as bands, venues, labels, studios, and more. Mixing those in a single network can quickly create messy attribution and security issues if you\'re not careful.\n\nSolution: Every social object stores both the user_id and the optional entity_id. Query helpers and hooks are entity-aware, so feeds, profile walls, notifications, and analytics always respect the current context while preserving a clear accountability trail.\n\n2. Balancing global discovery with follower relevance\nThe feed needed to feel alive and global, but still prioritize the artists, scenes, and entities a user actually cares about.\n\nSolution: The feed engine supports multiple modes (global, following-only, profile-specific) and blends follow relationships, recency, engagement, and content type into a simple scoring model. The result is predictable, tweakable ranking that doesn\'t feel like a black box.\n\n3. Handling rich media and cross-surface sharing\nPosts can include images, video, and links to blogs, news, or marketplace items — and they need to render correctly across dashboards, discovery tabs, and detail views without forking the UI for each surface.\n\nSolution: Media is normalized into a shared mapping layer, and posts can reference foreign resources (blogs, news, products) via explicit keys. Reusable components understand these relationships and adjust layouts automatically based on the attached content.\n\n4. Keeping engagement state accurate and responsive\nRapid interactions (likes, unlikes, multiple comments) can easily cause out-of-sync counts or duplicate records if the system isn\'t carefully designed.\n\nSolution: Engagement endpoints are idempotent and entity-aware, checking for existing records before inserting new ones. The UI uses optimistic updates with server reconciliation, and shared hooks centralize the logic so every interaction behaves the same way.\n\n5. Preserving performance with heavy feeds\nSocial feeds can grow large and media-heavy over time. They also appear in multiple layout sizes (full page, dashboard widget, overlays), where poor performance would be immediately obvious.\n\nSolution: Infinite scroll, intersection observers, memoized selectors, and skeleton states keep the experience feeling fast. Expensive work (analytics, deeper personalization) is batched or deferred so reading and posting never feel blocked.',
      impact: 'This social networking system is what turns SoundVent from "a collection of features" into a living community. It connects profiles, discovery, content, and analytics into a single, coherent experience where artists and fans don\'t just consume — they interact, react, and build relationships.\n\nOn the engineering side, it established a reusable pattern for entity-aware, engagement-driven features: clear identity modeling, strongly typed hooks and components, and tightly constrained APIs that are safe to reuse in new surfaces without rewriting core logic.\n\nFor users, the result feels music-native: expressive, conversational, and deeply woven into everything else they do on the platform — from discovering new artists to following labels to sharing clips with their scene.',
    },
  },
  {
    slug: 'kavalkade',
    title: 'Kavalkade — A Modern Music, Media & Merch Experience Built with Next.js',
    role: 'Founder & Lead Engineer',
    summary: 'A full-stack, immersive music experience for my own band — persistent audio, dynamic media, ecommerce, fan accounts, and a custom UI system. Essentially a mini–music platform built from scratch using the same tech and architecture I use for high-end app builds.',
    tags: ['Music', 'Ecommerce', 'Next.js', 'Stripe', 'Supabase', 'Printful', 'Audio Player', 'Full-Stack'],
    tech: ['Next.js', 'React', 'Stripe', 'Printful', 'Supabase', 'Zustand', 'TypeScript', 'TailwindCSS'],
    featured: true,
    featuredGridImage: '/images/portfolios/kavalkade-grid.jpg',
    featuredImage: '/images/portfolios/kavalkade.png',
    video: '/videos/kavalkade-next-js-app-min.mp4',
    showOverlay: true,
    description: 'Kavalkade\'s website wasn\'t meant to be "just another band page." I built it as a full-stack, immersive experience — persistent audio, dynamic media, ecommerce, fan accounts, and a custom UI system. It\'s essentially a mini–music platform built from scratch for my own band, using the same tech and architecture I use for high-end app builds.',
    caseStudySections: {
      overview: 'The goal was clear: create a fast, cinematic, next-gen home for the band — something that combines music streaming, video/photo galleries, and merch into one unified product.\n\nI designed and built the entire system using Next.js, leveraging Server Components, shared state management, and a persistent audio engine. Fans can listen to music while browsing media or shopping, without interruption.\n\nOn top of that, I integrated a complete ecommerce workflow with Stripe, Printful, and Supabase to handle accounts, auth, and order visibility.',
      architecture: 'Kavalkade\'s site is structured like a production-grade application rather than a simple website. The main features sit inside a layered architecture that keeps everything modular and scalable:\n\n• Next.js App Router for clean routing and segmented domains\n• Server Components for data-heavy pages and SEO-critical surfaces\n• Client Components for interactivity (player, cart, media viewer)\n• Global Zustand Store managing audio, cart state, and UI context\n• Singleton audio engine preserved across all navigation\n• Supabase Auth handling logins, accounts, and secure user data\n• Stripe for payment intents and checkout\n• Printful API for automated fulfillment\n\nNothing reloads unnecessarily. The audio engine never unmounts. Pages are lightweight, composable, and fast — the way a music experience should feel.',
      uiux: 'The design direction was inspired by Kavalkade\'s aesthetic: dark, minimal, moody, modern. I built a fully custom component system — buttons, cards, media grids, modals, layout primitives — all with consistent spacing, typography, and motion.\n\nEvery part of the UI is crafted to feel smooth and intentional:\n• A sticky global audio player with animated transitions\n• A full-screen music panel with artwork + track details\n• A responsive media grid for both photos and videos\n• Auto-playing video previews (desktop only)\n• Cinematic modal viewer for photos + videos\n• A clean, minimal storefront experience\n• A simple, fan-friendly account dashboard\n\nDesktop feels premium. Mobile feels tight and frictionless. The experience is cohesive across every touchpoint.',
      challenges: '1. Continuous music playback across routes\nTraditional sites break audio on navigation.\nSolution: a singleton global audio engine in a persistent layout + global store that keeps playback alive across all pages.\n\n2. Handling both images and video in the media grid\nDifferent formats = different behaviors and load strategies.\nSolution: a unified media card component with intelligent detection, lazy loading, and dynamic rendering.\n\n3. Integrating ecommerce seamlessly into the fan experience\nFans should be able to shop without losing their place in the listening experience.\nI built a SPA-like cart system using global state + Stripe checkout + Printful fulfillment.\n\n4. Making the site feel like a real app, not a template\nI built a custom design system from scratch — no templates, no theme boilerplate — ensuring the entire product feels cohesive and intentional.',
      impact: 'The finished product feels nothing like a traditional band site — it\'s closer to a mini streaming platform, merch store, and media hub blended into one.\n\nIt gives our fans:\n• A persistent listening experience\n• Fast, clean access to all media\n• A frictionless way to support the band with merch\n• A modern UI that matches the identity of our music\n\nFor me, it represents the level of polish and execution I bring to the apps I build — thoughtful architecture, a cohesive design system, and an obsessive focus on user experience end to end.',
    },
  },
  {
    slug: 'soundvent-persistent-music-player',
    title: 'SoundVent Persistent Music Player',
    role: 'Founder & Lead Engineer',
    summary: 'A unified audio system powering continuous playback across the entire SoundVent platform — a singleton audio engine that keeps music playing seamlessly as users browse profiles, scroll feeds, and explore the marketplace.',
    tags: ['SaaS', 'Music', 'Audio Player', 'State Management', 'Next.js', 'React', 'Web Audio'],
    tech: ['Next.js', 'React', 'Zustand', 'Web Audio API', 'TypeScript', 'TailwindCSS', 'HTML5 Audio'],
    featured: false,
    featuredGridImage: '/images/portfolios/sv-persistent-music-player-grid.jpg',
    featuredImage: '/images/portfolios/sv-persistent-music-player.png',
    showOverlay: false,
    description: 'A unified audio system powering continuous playback across the entire platform. The persistent music player is one of the foundational systems inside SoundVent — a continuous, platform-wide audio engine that allows listeners to browse profiles, scroll through feeds, open posts, and explore music without ever interrupting playback. Unlike traditional audio widgets or page-scoped players, SoundVent\'s player is built as a true singleton: one audio engine, one global state, and seamless continuity across every route and interface.',
    caseStudySections: {
      overview: 'The SoundVent music experience needed to feel as fluid as modern streaming apps — no stopping, no reloads, no restarts. To accomplish this, I designed a persistent audio system that sits at the core of the platform. It controls playback, manages queues, syncs progress, and handles all UI interactions, all while remaining mounted across every navigation.\n\nWhether users are checking out artists, scrolling through posts, or exploring the marketplace, their music keeps playing. The player is always available, always in sync, and behaves consistently no matter where they are in the app.',
      architecture: 'The SoundVent player is built as a singleton — a single instance that owns audio playback across the entire application. This ensures that music continues uninterrupted, and all UI components talk to the same engine.\n\nKey architectural elements include:\n• Singleton Audio Engine — The audio engine is instantiated once and shared globally. UI components never create their own audio instances; they communicate through a central controller to avoid conflicts or duplicated playback.\n• Global Store Integration — The player exposes its state and actions through a platform-level store, allowing any part of the UI to update the queue, switch tracks, pause, resume, or seek.\n• Persistent Layout Layer — The player lives inside a non-unmounting layout boundary. This ensures both the player component and the audio engine remain alive as users navigate the app.\n• Event-Driven Syncing — The audio engine syncs changes back to the store through event listeners for timeupdate, play, pause, ended, and metadata loading.\n• Waveform & Visualization Layer — The player exposes an analyzer node from the singleton engine to power waveform and spectrum visualizations across multiple components.\n\nThis architecture allows SoundVent to deliver a streaming experience that feels native, responsive, and reliable — exactly what users expect from a modern music platform.',
      uiux: 'The UI is designed to be familiar, approachable, and performance-focused. It blends in with the SoundVent design system while maintaining its own identity as a platform-level utility.\n\nUX highlights include:\n• Bottom-anchored player bar that\'s always available without interrupting browsing.\n• Expandable player view with artwork, timeline, queue controls, and playback details.\n• Minimized state for users who want to browse without visual distraction.\n• Queue management that lets listeners build or modify a session on the fly.\n• Real-time visualizer driven by the singleton engine\'s analyzer node.\n\nThe overall goal was to make playback feel effortless — a stable companion to the rest of the platform rather than a standalone feature.',
      challenges: '1. Ensuring audio never restarts on navigation\nTraditional routing reloads audio elements, which instantly breaks continuity.\nSolution: The player and audio engine live inside a persistent layout layer that never unmounts. Routes load underneath it.\n\n2. Preventing duplicate audio engine instances\nMultiple mounts would cause overlapping playback, unsynced UI, and inconsistent state.\nSolution: A true singleton pattern ensures only one audio engine ever exists. All UI modules reference the same instance.\n\n3. Keeping progress, UI, and state in sync\nAudio events need to reflect instantly in the UI, and UI controls need to update the engine without lag.\nSolution: Event listeners fire updates into the global store, and UI actions route back to the engine through a unified API.\n\n4. Integrating waveform visualization safely\nThe audio visualization layer required the Web Audio API, which can\'t be initialized prematurely or multiple times.\nSolution: The analyzer is created once at engine initialization and fed into visualizers on demand.\n\n5. Maintaining performance with heavy UI\nA music player should never slow down browsing or affect scroll performance.\nSolution: Decoupled rendering, throttled state updates, and a highly optimized visualizer.',
      impact: 'The persistent music player became a defining feature of SoundVent — a core part of the user experience that makes the platform feel alive, cohesive, and modern. It elevates browsing into a continuous listening session and reinforces the platform\'s identity as a place where music and interaction coexist seamlessly.\n\nFor the broader system, it demonstrates a scalable pattern: platform-wide features powered by singleton engines, global state, and persistent layouts. This pattern informs many other parts of SoundVent\'s architecture.\n\nFor users, it creates an experience that feels premium, stable, and expressive — exactly the tone SoundVent was built to set.',
    },
  },
  {
    slug: 'soundvent-product-creator',
    title: 'SoundVent Product Creation App',
    role: 'Founder & Lead Engineer',
    summary: 'A fully custom, multi-step product builder designed for creators — a Shopify-grade product creation tool with variant management, autosaving, and real-time validation, built entirely within the SoundVent platform.',
    tags: ['Ecommerce', 'Product Builder', 'Creator Tools', 'SaaS', 'Next.js', 'Supabase'],
    tech: ['Next.js', 'React', 'Supabase', 'PostgreSQL', 'Zustand', 'TailwindCSS', 'shadcn/ui', 'TypeScript'],
    featured: true,
    featuredGridImage: '/images/portfolios/sv-product-creator-grid.jpg',
    featuredImage: '/images/portfolios/sv-product-creator.png',
    showOverlay: false,
    description: 'The SoundVent Product Creation App is a core part of the platform\'s marketplace ecosystem — a fully custom-built tool that allows creators to design, manage, and publish products with the same level of polish and control they\'d expect from Shopify or Printful. Instead of relying on third-party dashboards, the system gives SoundVent complete flexibility over product data, media, workflows, and presentation.',
    caseStudySections: {
      overview: 'At its core, the product builder is a structured, multi-step creation flow designed for clarity and precision. Creators can upload images, configure variants, define pricing, and map metadata — all with live validation, autosaving, and real-time UI feedback. The system is deeply integrated with Supabase, allowing product data, variants, images, and relationships to be stored cleanly and accessed throughout the platform.\n\nThe result is a scalable foundation for SoundVent\'s commerce layer, engineered to support both simple creator products and more sophisticated multi-variant offerings.',
      architecture: 'The Product Creation App is built using Next.js, Supabase, Zustand, and a modular component system shared across the entire SoundVent platform.\n\nKey architectural concepts:\n• Step-based workflow — Each step — details, images, variants, pricing, publish settings — is independently validated and saved\n• Autosaving with Supabase — Data writes occur as the user progresses, preventing loss and keeping drafts consistent\n• Relational product schema — Products, variants, images, categories, and metadata are normalized into clean join tables for long-term scalability\n• Global state for in-progress product data — Zustand handles local editing state before syncing changes to Supabase\n• Async media handling — Images are uploaded to Supabase Storage, processed, and immediately available inside the UI\n• Strict type safety — Every field, step, and validation rule is fully typed to prevent malformed product configurations\n\nThis architecture allows the builder to behave like a desktop app while remaining entirely web-based and serverless.',
      uiux: 'The interface is designed around clarity and low cognitive load — a guided process that helps creators move step-by-step without overwhelm.\n\nHighlights include:\n• Clean, step-driven layout that mirrors enterprise dashboards\n• Instant visual feedback: image previews, live error states, and contextual helpers\n• Variant matrix UI for handling complex combinations\n• Autosave indicators so users never worry about losing work\n• Consistent components from SoundVent\'s design system for a seamless, predictable feel\n• Responsive grid layouts that adapt to any screen size\n• A "draft vs publish" workflow that feels intuitive and reduces mistakes\n\nThe goal was to give creators a powerful tool disguised as a simple one — professional capability with a frictionless experience.',
      challenges: '1. Keeping the workflow smooth across many steps\nLarge creation flows often feel heavy. To avoid this, each step loads only the required data and writes asynchronously.\nSolution: modular steps, Zustand local staging, Supabase row updates per step.\n\n2. Handling complex product variants\nVariants quickly become messy when mixing sizes, colors, and images.\nSolution: a dynamic variant matrix that generates combinations, validates them, and stores them in a clean relational structure.\n\n3. Preventing data loss during long editing sessions\nCreators often move back and forth between steps or leave mid-session.\nSolution: autosave on every meaningful change, backed by "draft" tables and optimistic UI.\n\n4. Integrating media uploads smoothly\nImages need to upload quickly, appear instantly, and map correctly to products or variants.\nSolution: media uploads flow through Supabase Storage with local preview support and immediate syncing.\n\n5. Ensuring the builder could grow with SoundVent\nThe system needed to support more than v1 features.\nSolution: strictly typed data models, predictable component patterns, and normalized relationships.',
      impact: 'The Product Creation App became a cornerstone of SoundVent\'s marketplace architecture. It transformed product creation from a manual, error-prone process into a guided, professional workflow that creators could trust.\n\nFor the platform, it unlocked:\n• Consistent, structured product data\n• A scalable foundation for marketplace features\n• Seamless integration with media, profiles, and commerce flows\n• A fully custom system that doesn\'t depend on external dashboards\n\nAnd for creators, it provided a clean, intuitive way to publish products without learning a new platform — a natural extension of the SoundVent environment.',
    },
  },
  {
    slug: 'portfolio-site',
    title: 'Portfolio Site',
    role: 'Solo Developer',
    summary: 'A production-ready portfolio site built in 24 hours, showcasing modern Next.js architecture, persistent audio player, developer tools, command palette, and responsive design — demonstrating rapid full-stack development capabilities.',
    tags: ['Portfolio', 'Next.js', 'TypeScript', 'Performance', 'Developer Tools'],
    tech: ['Next.js 16', 'React 18', 'TypeScript', 'TailwindCSS', 'Framer Motion', 'Zustand', 'Radix UI', 'shadcn/ui', 'Next Themes', 'CMDK', 'Sonner'],
    featured: false,
    featuredGridImage: '/images/portfolios/portfolio-portfolio-grid.jpg',
    featuredImage: '/images/portfolios/portfolio-portfolio.png',
    description: 'Built entirely in 24 hours, this portfolio site demonstrates rapid full-stack development with modern web technologies. The site features a persistent audio player with waveform visualization, developer-focused tools including an inspector overlay and mini terminal, a VS Code-style command palette, responsive design across all breakpoints, and smooth animations throughout. Every component is production-ready, fully typed, and optimized for performance.',
    caseStudySections: {
      overview: 'This portfolio site was conceived, designed, and built from scratch in a single 24-hour sprint. The goal was to create a production-ready showcase that demonstrates not just design skills, but deep technical capabilities — including complex state management, real-time features, developer tools, and modern React patterns. The site serves as both a portfolio and a technical demonstration, featuring advanced features like a persistent audio player, component inspector, command palette, and fully responsive layouts.',
      architecture: '• Next.js 16 App Router with TypeScript for type-safe, server-rendered pages\n• React Server Components for optimal performance and SEO\n• Zustand for lightweight, performant state management:\n  • UI store (theme, panels, dialogs, inspect mode)\n  • Player store (queue, playback state, position)\n  • Persistent storage via Zustand middleware\n• Framer Motion for smooth animations and scroll-based effects:\n  • Scroll-triggered parallax effects\n  • Page transitions\n  • Component entrance animations\n  • Carousel transitions\n• Radix UI + shadcn/ui for accessible, customizable components\n• Custom cursor system with context-aware states\n• Component inspector overlay using DOM traversal and data attributes\n• Command palette (CMDK) with keyboard navigation\n• Mini terminal with command execution and FAQ system\n• Persistent audio player with HTML5 Audio API\n• Waveform visualizer (placeholder for future Web Audio API integration)\n• Theme system with light/dark/studio modes via next-themes\n• Responsive design with mobile-first approach\n• Optimized images with Next.js Image component\n• Font optimization with next/font (DM Mono, Inter)',
      uiux: '• Modern, minimal design language with consistent spacing and typography\n• Fully responsive layouts that elegantly scale from mobile to desktop\n• Smooth animations and transitions throughout\n• Custom cursor with context-aware states (link, tap, text)\n• Persistent audio player that survives navigation\n• VS Code-inspired editor navigation panel\n• Command palette (⌘K / Ctrl+K) for quick navigation\n• Developer tools (inspector overlay, mini terminal) for technical demonstration\n• Theme panel with live preview\n• Settings sheet for customization\n• Contact dialog with form handling\n• Smooth scroll animations and parallax effects\n• Carousel components with fade transitions\n• Hover effects and micro-interactions\n• Mobile hamburger menu with full navigation\n• Accessible components with proper ARIA labels',
      challenges: 'Challenges:\n• Building a complete, production-ready site in 24 hours\n• Implementing persistent audio player that survives Next.js navigation\n• Creating component inspector that accurately identifies React components\n• Building command palette with complex routing and action handling\n• Managing multiple overlapping UI states (panels, dialogs, modals)\n• Implementing smooth animations without performance degradation\n• Creating responsive layouts that maintain design integrity\n• Handling theme persistence across page reloads\n• Optimizing bundle size while including many features\n• TypeScript type safety across complex state management\n• Ensuring accessibility while maintaining modern UX\n• Mobile navigation UX that doesn\'t compromise desktop experience\n\nSolutions:\n• Leveraged Next.js App Router for optimal performance and SEO\n• Used Zustand for simple, performant state management\n• Implemented data-component and data-file attributes for component identification\n• Built modular component architecture for reusability\n• Used Framer Motion for GPU-accelerated animations\n• Implemented mobile-first responsive design patterns\n• Used next-themes for seamless theme persistence\n• Optimized images and fonts for fast loading\n• Implemented proper TypeScript types throughout\n• Used Radix UI for accessible, unstyled primitives\n• Created consistent design system with TailwindCSS\n• Tested across multiple devices and browsers',
      impact: '• Delivered a fully functional, production-ready portfolio in 24 hours\n• Demonstrated rapid development capabilities with modern tech stack\n• Showcased advanced features including:\n  • Persistent audio player\n  • Developer tools (inspector, terminal)\n  • Command palette navigation\n  • Responsive design\n  • Smooth animations\n• Created a technical showcase that demonstrates:\n  • Full-stack capabilities\n  • Modern React/Next.js expertise\n  • UI/UX design skills\n  • Performance optimization\n  • TypeScript proficiency\n• Built a maintainable codebase with:\n  • Clear component structure\n  • Type-safe state management\n  • Reusable UI components\n  • Consistent design patterns\n• Established foundation for future enhancements:\n  • Blog system\n  • Portfolio case studies\n  • Lab experiments\n  • Additional interactive features',
    },
  },
  {
    slug: 'dwarven-forge',
    title: 'Dwarven Forge — Custom Search Engine & Platform Enhancements',
    role: 'Senior Shopify / Next.js Engineer',
    summary: 'Engineered a high-performance custom Next.js + Algolia search application and optimized their Shopify architecture, enabling millisecond search over thousands of SKUs, major theme upgrades, custom UI systems, dynamic product recommendations, and large-scale catalog support.',
    tags: ['Ecommerce', 'Search', 'Performance', 'Shopify', 'Next.js', 'Algolia'],
    tech: ['Next.js', 'React', 'Algolia', 'Shopify Storefront API', 'Shopify Admin API', 'Liquid', 'TailwindCSS', 'Vercel'],
    featured: true,
    featuredGridImage: '/images/portfolios/df-portfolio-grid.jpg',
    featuredImage: '/images/portfolios/df-portfolio.png',
    description: 'Dwarven Forge — a globally recognized brand in tabletop terrain — needed a search and browsing experience capable of handling thousands of complex product variations with speed, accuracy, and intuitive UX. I architected and built a completely custom Next.js search application using Algolia, transforming performance from multi-second delays into millisecond responses. Beyond search, I rebuilt major parts of their Shopify theme: new homepages, PDPs, collection templates, AJAX cart features, dynamic recommendations, and UI improvements — all while optimizing for the enormous volume and complexity of their inventory system.',
    caseStudySections: {
      overview: 'Dwarven Forge sells highly detailed, modular tabletop terrain kits with hundreds of SKUs and massive product bundles. Their standard Shopify apps and theme setup couldn\'t scale — search was slow, filtering was limited, and browsing thousands of SKUs caused performance issues.\n\nI was brought in to rebuild the foundation:\n• A custom high-speed search engine\n• New Next.js UI for product discovery\n• Theme upgrades and large-scale architecture improvements\n• Seamless AJAX-based cart workflows\n• Real-time product recommendations\n• Handling thousands of products with complex inventory structures',
      architecture: '• Next.js + Algolia InstantSearch for millisecond search results\n• Server-side indexing pipeline syncing Shopify -> Algolia\n• Dynamic ranking rules tailored for terrain categories and attributes\n• Optimized Shopify Storefront API queries for PDP & collection enhancements\n• Shopify Admin API for advanced product data access\n• Custom Liquid theme upgrades, including:\n  • Rebuilt homepage\n  • Faster collection pages\n  • Overhauled PDP UX\n• AJAX cart system supporting:\n  • Quick add\n  • Real-time inventory checks\n  • Upsell recommendations\n• Custom product recommendation engine analyzing:\n  • Cart contents\n  • User behavior\n  • Product relationships\n• Performance restructuring:\n  • Script deferrals\n  • Image optimization\n  • Lazy loading\n  • CSS reduction\n  • Fixing multiple long-standing theme bottlenecks',
      uiux: '• New modular homepage layout\n• Improved collection filtering UX\n• Rebuilt product detail pages with clean component-based structure\n• Faster engagement paths for adding products to cart\n• Search UI that feels instant and responsive (true "app-like search")\n• Modernized design system for buttons, cards, and product blocks\n• Vastly clearer mobile navigation and product browsing flow',
      challenges: 'Challenges:\n• Indexing thousands of SKUs with deeply nested product options\n• Replacing slow Shopify-native search with custom Algolia\n• Optimizing legacy theme code filled with performance issues\n• Building predictive product recommendations\n• Handling large collection pages with heavy media\n• Delivering millisecond search for complex inventory categories\n• Integrating multiple APIs (Storefront, Admin, custom feeds)\n\nSolutions:\nArchitected a full indexing pipeline, modularized the theme, used advanced Algolia indexing rules, implemented caching layers, and rebuilt multiple UI components from scratch for clarity and speed.',
      impact: '• Search performance improved from >2 seconds → <50ms\n• Dramatically improved user navigation and product discoverability\n• Reduced bounce rates on key collection pages\n• Increased cart engagement with smart AJAX flows\n• Built future-proof search infrastructure for large catalog growth\n• Delivered a premium, app-like browsing experience on Shopify\n• Reduced theme code complexity and long-term maintenance cost',
    },
  },
  {
    slug: 'soundvent',
    title: 'SoundVent',
    role: 'Founder & Lead Engineer',
    summary: 'A next-generation, all-in-one music platform that unifies social networking, music and video streaming, messaging, ecommerce, fan engagement, events, and creator tools into one seamless ecosystem — fully architected and engineered from scratch.',
    tags: ['SaaS', 'Music', 'Social Network', 'Ecommerce', 'Real-time', 'Video', 'Streaming', 'Creator Tools'],
    tech: ['Next.js', 'React', 'Supabase', 'PostgreSQL', 'Stripe Connect', 'Mux', 'TailwindCSS', 'shadcn/ui', 'Zustand', 'Radix', 'Vercel'],
    featured: true,
    featuredGridImage: '/images/portfolios/sv-portfolio-grid.jpg',
    featuredImage: '/images/portfolios/sv-portfolio.png',
    description: 'SoundVent is a unified music and creator platform built from the ground up to solve the fragmentation artists face across Spotify, Instagram, Shopify, TikTok, YouTube, and Ticketmaster. Designed by musicians and engineered with modern, high-performance web technologies, SoundVent blends social networking, real-time messaging, media streaming, and a fully featured product/merch engine into a single cohesive application. Over 5 months, the product evolved into a 10-in-1 ecosystem: profiles, feeds, video, messaging, ecommerce, events, analytics, discovery, merchandising, and more — all production-ready and scalable.',
    caseStudySections: {
      overview: 'SoundVent began as a decade-old vision: a unified platform where artists could share music, build community, sell merch, host events, and connect directly with fans — without relying on a messy patchwork of third-party tools. As Founder & Lead Engineer, I architected and built the entire application solo over 5 months, combining modern frameworks like Next.js and Supabase to deliver a fast, robust, real-time experience. The platform launched with a fully integrated social network, real-time messaging system, music/video upload pipeline, and a complete Shopify-grade product creator and merch system.',
      architecture: '• Next.js 14 App Router for server components, streaming, and hybrid rendering\n• Supabase (Postgres + Auth + Storage + Realtime) powering:\n  • Profiles & roles\n  • Real-time feed\n  • Follower graph\n  • Social posts, comments, likes\n  • Messaging system\n  • Products, variants, categories, inventory\n  • Events + ticketing foundations\n• Mux for video encoding, streaming, thumbnails, analytics\n• Stripe Connect for multi-vendor commerce and payouts\n• Custom REST actions & RLS-secured APIs for write operations\n• Zustand + React Query for UI state and caching\n• Tailwind + shadcn/ui for a scalable design system\n• Optimized media manager with albums, tags, bucket routing, and TipTap integration\n• Unified schema for music, video, posts, comments, likes, merch, events\n• Elastic real-time notifications via Supabase channels\n• Robust RLS policies ensuring artist/fan permissions and private data protection',
      uiux: '• Built a mobile-first UI with smooth transitions, animations, and a cohesive music-oriented aesthetic\n• Designed a full social feed experience with real-time updates\n• Built a complete merch/product creator UX rivaling Shopify\'s variant editor\n• Designed artist dashboards, analytics UIs, event pages, and follower sections\n• Implemented dark mode, persistent music player, drag-and-drop media management\n• Created a clean, modern brand identity using SoundVent\'s emblem and gold-on-black theme',
      challenges: 'Challenges:\n• Building 10+ major modules as a solo dev\n• Architecting a real-time social network + messaging system\n• Handling large media uploads (images, video) with secure access\n• Designing 30+ database tables with tight RLS policies\n• Balancing SSR, client components, caching, and reactivity\n• Crafting a Shopify-level product/variant system from scratch\n• Managing Supabase quirks, middleware edge cases, and hydration issues\n• Creating a unified UI that didn\'t feel overwhelming despite massive feature depth\n\nSolutions:\nLeveraged modern Next.js patterns, modularized DB schemas, wrote custom Supabase helpers, implemented structured state management, tested extensively, and iterated rapidly while maintaining scalable architecture.',
      impact: '• Shipped a production-ready beta in 5 months of solo development\n• Delivered a unified creator ecosystem unprecedented in indie music tech\n• Built a platform capable of supporting future:\n  • Mobile apps\n  • Live streaming\n  • Ticketing\n  • POD merch\n  • AI-assisted tools\n• Attracted immediate interest from artists, creators, engineers, and investors\n• Created one of the most fully featured indie SaaS platforms in the music space',
    },
  },
];

