export type Project = {
  slug: string;
  title: string;
  role: string;
  summary: string;
  tags: string[];
  tech: string[];
  featured: boolean;
  description: string;
  featuredImage?: string; // Path to featured image (e.g., '/images/portfolios/image.png')
  caseStudySections?: {
    overview?: string;
    architecture?: string;
    uiux?: string;
    challenges?: string;
    impact?: string;
  };
};

export const projects: Project[] = [
  {
    slug: 'soundvent',
    title: 'SoundVent',
    role: 'Founder & Lead Engineer',
    summary: 'A next-generation, all-in-one music platform that unifies social networking, music and video streaming, messaging, ecommerce, fan engagement, events, and creator tools into one seamless ecosystem — fully architected and engineered from scratch.',
    tags: ['SaaS', 'Music', 'Social Network', 'Ecommerce', 'Real-time', 'Video', 'Streaming', 'Creator Tools'],
    tech: ['Next.js', 'React', 'Supabase', 'PostgreSQL', 'Stripe Connect', 'Mux', 'TailwindCSS', 'shadcn/ui', 'Zustand', 'Radix', 'Vercel'],
    featured: true,
    featuredImage: '/images/portfolios/sv-portfolio.png',
    description: 'SoundVent is a unified music and creator platform built from the ground up to solve the fragmentation artists face across Spotify, Instagram, Shopify, TikTok, YouTube, and Ticketmaster. Designed by musicians and engineered with modern, high-performance web technologies, SoundVent blends social networking, real-time messaging, media streaming, and a fully featured product/merch engine into a single cohesive application. Over 5 months, the product evolved into a 10-in-1 ecosystem: profiles, feeds, video, messaging, ecommerce, events, analytics, discovery, merchandising, and more — all production-ready and scalable.',
    caseStudySections: {
      overview: 'SoundVent began as a decade-old vision: a unified platform where artists could share music, build community, sell merch, host events, and connect directly with fans — without relying on a messy patchwork of third-party tools. As Founder & Lead Engineer, I architected and built the entire application solo over 5 months, combining modern frameworks like Next.js and Supabase to deliver a fast, robust, real-time experience. The platform launched with a fully integrated social network, real-time messaging system, music/video upload pipeline, and a complete Shopify-grade product creator and merch system.',
      architecture: '• Next.js 14 App Router for server components, streaming, and hybrid rendering\n• Supabase (Postgres + Auth + Storage + Realtime) powering:\n  • Profiles & roles\n  • Real-time feed\n  • Follower graph\n  • Social posts, comments, likes\n  • Messaging system\n  • Products, variants, categories, inventory\n  • Events + ticketing foundations\n• Mux for video encoding, streaming, thumbnails, analytics\n• Stripe Connect for multi-vendor commerce and payouts\n• Custom REST actions & RLS-secured APIs for write operations\n• Zustand + React Query for UI state and caching\n• Tailwind + shadcn/ui for a scalable design system\n• Optimized media manager with albums, tags, bucket routing, and TipTap integration\n• Unified schema for music, video, posts, comments, likes, merch, events\n• Elastic real-time notifications via Supabase channels\n• Robust RLS policies ensuring artist/fan permissions and private data protection',
      uiux: '• Built a mobile-first UI with smooth transitions, animations, and a cohesive music-oriented aesthetic\n• Designed a full social feed experience with real-time updates\n• Built a complete merch/product creator UX rivaling Shopify\'s variant editor\n• Designed artist dashboards, analytics UIs, event pages, and follower sections\n• Implemented dark mode, persistent music player, drag-and-drop media management\n• Created a clean, modern brand identity using SoundVent\'s emblem and gold-on-black theme',
      challenges: 'Challenges:\n• Building 10+ major modules as a solo dev\n• Architecting a real-time social network + messaging system\n• Handling large media uploads (images, video) with secure access\n• Designing 30+ database tables with tight RLS policies\n• Balancing SSR, client components, caching, and reactivity\n• Crafting a Shopify-level product/variant system from scratch\n• Managing Supabase quirks, middleware edge cases, and hydration issues\n• Creating a unified UI that didn\'t feel overwhelming despite massive feature depth\n\nSolutions:\nLeveraged modern Next.js patterns, modularized DB schemas, wrote custom Supabase helpers, implemented structured state management, tested extensively, and iterated rapidly while maintaining scalable architecture.',
      impact: '• Shipped a production-ready beta in 5 months of solo development\n• Delivered a unified creator ecosystem unprecedented in indie music tech\n• Built a platform capable of supporting future:\n  • Mobile apps\n  • Live streaming\n  • Ticketing\n  • POD merch\n  • AI-assisted tools\n• Attracted immediate interest from artists, creators, engineers, and investors\n• Created one of the most fully featured indie SaaS platforms in the music space',
    },
  },
  {
    slug: 'dwarven-forge',
    title: 'Dwarven Forge — Custom Search Engine & Platform Enhancements',
    role: 'Senior Shopify / Next.js Engineer',
    summary: 'Engineered a high-performance custom Next.js + Algolia search application and optimized their Shopify architecture, enabling millisecond search over thousands of SKUs, major theme upgrades, custom UI systems, dynamic product recommendations, and large-scale catalog support.',
    tags: ['Ecommerce', 'Search', 'Performance', 'Shopify', 'Next.js', 'Algolia'],
    tech: ['Next.js', 'React', 'Algolia', 'Shopify Storefront API', 'Shopify Admin API', 'Liquid', 'TailwindCSS', 'Vercel'],
    featured: true,
    featuredImage: '/images/portfolios/df-portfolio.png',
    description: 'Dwarven Forge — a globally recognized brand in tabletop terrain — needed a search and browsing experience capable of handling thousands of complex product variations with speed, accuracy, and intuitive UX. I architected and built a completely custom Next.js search application using Algolia, transforming performance from multi-second delays into millisecond responses. Beyond search, I rebuilt major parts of their Shopify theme: new homepages, PDPs, collection templates, AJAX cart features, dynamic recommendations, and UI improvements — all while optimizing for the enormous volume and complexity of their inventory system.',
    caseStudySections: {
      overview: 'Dwarven Forge sells highly detailed, modular tabletop terrain kits with hundreds of SKUs and massive product bundles. Their standard Shopify apps and theme setup couldn\'t scale — search was slow, filtering was limited, and browsing thousands of SKUs caused performance issues.\n\nI was brought in to rebuild the foundation:\n• A custom high-speed search engine\n• New Next.js UI for product discovery\n• Theme upgrades and large-scale architecture improvements\n• Seamless AJAX-based cart workflows\n• Real-time product recommendations\n• Handling thousands of products with complex inventory structures',
      architecture: '• Next.js + Algolia InstantSearch for millisecond search results\n• Server-side indexing pipeline syncing Shopify -> Algolia\n• Dynamic ranking rules tailored for terrain categories and attributes\n• Optimized Shopify Storefront API queries for PDP & collection enhancements\n• Shopify Admin API for advanced product data access\n• Custom Liquid theme upgrades, including:\n  • Rebuilt homepage\n  • Faster collection pages\n  • Overhauled PDP UX\n• AJAX cart system supporting:\n  • Quick add\n  • Real-time inventory checks\n  • Upsell recommendations\n• Custom product recommendation engine analyzing:\n  • Cart contents\n  • User behavior\n  • Product relationships\n• Performance restructuring:\n  • Script deferrals\n  • Image optimization\n  • Lazy loading\n  • CSS reduction\n  • Fixing multiple long-standing theme bottlenecks',
      uiux: '• New modular homepage layout\n• Improved collection filtering UX\n• Rebuilt product detail pages with clean component-based structure\n• Faster engagement paths for adding products to cart\n• Search UI that feels instant and responsive (true "app-like search")\n• Modernized design system for buttons, cards, and product blocks\n• Vastly clearer mobile navigation and product browsing flow',
      challenges: 'Challenges:\n• Indexing thousands of SKUs with deeply nested product options\n• Replacing slow Shopify-native search with custom Algolia\n• Optimizing legacy theme code filled with performance issues\n• Building predictive product recommendations\n• Handling large collection pages with heavy media\n• Delivering millisecond search for complex inventory categories\n• Integrating multiple APIs (Storefront, Admin, custom feeds)\n\nSolutions:\nArchitected a full indexing pipeline, modularized the theme, used advanced Algolia indexing rules, implemented caching layers, and rebuilt multiple UI components from scratch for clarity and speed.',
      impact: '• Search performance improved from >2 seconds → <50ms\n• Dramatically improved user navigation and product discoverability\n• Reduced bounce rates on key collection pages\n• Increased cart engagement with smart AJAX flows\n• Built future-proof search infrastructure for large catalog growth\n• Delivered a premium, app-like browsing experience on Shopify\n• Reduced theme code complexity and long-term maintenance cost',
    },
  },
  {
    slug: 'portfolio-site',
    title: 'Portfolio Site',
    role: 'Solo Developer',
    summary: 'A production-ready portfolio site built in 24 hours, showcasing modern Next.js architecture, persistent audio player, developer tools, command palette, and responsive design — demonstrating rapid full-stack development capabilities.',
    tags: ['Portfolio', 'Next.js', 'TypeScript', 'Performance', 'Developer Tools'],
    tech: ['Next.js 16', 'React 18', 'TypeScript', 'TailwindCSS', 'Framer Motion', 'Zustand', 'Radix UI', 'shadcn/ui', 'Next Themes', 'CMDK', 'Sonner'],
    featured: false,
    featuredImage: '/images/portfolios/portfolio-portfolio.png',
    description: 'Built entirely in 24 hours, this portfolio site demonstrates rapid full-stack development with modern web technologies. The site features a persistent audio player with waveform visualization, developer-focused tools including an inspector overlay and mini terminal, a VS Code-style command palette, responsive design across all breakpoints, and smooth animations throughout. Every component is production-ready, fully typed, and optimized for performance.',
    caseStudySections: {
      overview: 'This portfolio site was conceived, designed, and built from scratch in a single 24-hour sprint. The goal was to create a production-ready showcase that demonstrates not just design skills, but deep technical capabilities — including complex state management, real-time features, developer tools, and modern React patterns. The site serves as both a portfolio and a technical demonstration, featuring advanced features like a persistent audio player, component inspector, command palette, and fully responsive layouts.',
      architecture: '• Next.js 16 App Router with TypeScript for type-safe, server-rendered pages\n• React Server Components for optimal performance and SEO\n• Zustand for lightweight, performant state management:\n  • UI store (theme, panels, dialogs, inspect mode)\n  • Player store (queue, playback state, position)\n  • Persistent storage via Zustand middleware\n• Framer Motion for smooth animations and scroll-based effects:\n  • Scroll-triggered parallax effects\n  • Page transitions\n  • Component entrance animations\n  • Carousel transitions\n• Radix UI + shadcn/ui for accessible, customizable components\n• Custom cursor system with context-aware states\n• Component inspector overlay using DOM traversal and data attributes\n• Command palette (CMDK) with keyboard navigation\n• Mini terminal with command execution and FAQ system\n• Persistent audio player with HTML5 Audio API\n• Waveform visualizer (placeholder for future Web Audio API integration)\n• Theme system with light/dark/studio modes via next-themes\n• Responsive design with mobile-first approach\n• Optimized images with Next.js Image component\n• Font optimization with next/font (DM Mono, Inter)',
      uiux: '• Modern, minimal design language with consistent spacing and typography\n• Fully responsive layouts that elegantly scale from mobile to desktop\n• Smooth animations and transitions throughout\n• Custom cursor with context-aware states (link, tap, text)\n• Persistent audio player that survives navigation\n• VS Code-inspired editor navigation panel\n• Command palette (⌘K / Ctrl+K) for quick navigation\n• Developer tools (inspector overlay, mini terminal) for technical demonstration\n• Theme panel with live preview\n• Settings sheet for customization\n• Contact dialog with form handling\n• Smooth scroll animations and parallax effects\n• Carousel components with fade transitions\n• Hover effects and micro-interactions\n• Mobile hamburger menu with full navigation\n• Accessible components with proper ARIA labels',
      challenges: 'Challenges:\n• Building a complete, production-ready site in 24 hours\n• Implementing persistent audio player that survives Next.js navigation\n• Creating component inspector that accurately identifies React components\n• Building command palette with complex routing and action handling\n• Managing multiple overlapping UI states (panels, dialogs, modals)\n• Implementing smooth animations without performance degradation\n• Creating responsive layouts that maintain design integrity\n• Handling theme persistence across page reloads\n• Optimizing bundle size while including many features\n• TypeScript type safety across complex state management\n• Ensuring accessibility while maintaining modern UX\n• Mobile navigation UX that doesn\'t compromise desktop experience\n\nSolutions:\n• Leveraged Next.js App Router for optimal performance and SEO\n• Used Zustand for simple, performant state management\n• Implemented data-component and data-file attributes for component identification\n• Built modular component architecture for reusability\n• Used Framer Motion for GPU-accelerated animations\n• Implemented mobile-first responsive design patterns\n• Used next-themes for seamless theme persistence\n• Optimized images and fonts for fast loading\n• Implemented proper TypeScript types throughout\n• Used Radix UI for accessible, unstyled primitives\n• Created consistent design system with TailwindCSS\n• Tested across multiple devices and browsers',
      impact: '• Delivered a fully functional, production-ready portfolio in 24 hours\n• Demonstrated rapid development capabilities with modern tech stack\n• Showcased advanced features including:\n  • Persistent audio player\n  • Developer tools (inspector, terminal)\n  • Command palette navigation\n  • Responsive design\n  • Smooth animations\n• Created a technical showcase that demonstrates:\n  • Full-stack capabilities\n  • Modern React/Next.js expertise\n  • UI/UX design skills\n  • Performance optimization\n  • TypeScript proficiency\n• Built a maintainable codebase with:\n  • Clear component structure\n  • Type-safe state management\n  • Reusable UI components\n  • Consistent design patterns\n• Established foundation for future enhancements:\n  • Blog system\n  • Portfolio case studies\n  • Lab experiments\n  • Additional interactive features',
    },
  },
];

